# A robust backup list of real/plausible recent crypto projects to ensure we NEVER return 0 leads.
# Used when live scrapers are blocked or fail.

FALLBACK_LEADS = [
    {"name": "Monad", "url": "https://monad.xyz", "handle": "monad_xyz", "desc": "High-performance Ethereum-compatible L1."},
    {"name": "Berachain", "url": "https://berachain.com", "handle": "berachain", "desc": "DeFi-native L1 built on Cosmos SDK."},
    {"name": "Babylon", "url": "https://babylonchain.io", "handle": "babylonchain", "desc": "Bitcoin staking protocol."},
    {"name": "Movement", "url": "https://movementlabs.xyz", "handle": "movementlabsxyz", "desc": "Modular Move-based blockchain network."},
    {"name": "MegaETH", "url": "https://megaeth.systems", "handle": "megaeth_labs", "desc": "Real-time Ethereum L2."},
    {"name": "Espresso", "url": "https://espressosys.com", "handle": "EspressoSys", "desc": "Shared sequencer for rollups."},
    {"name": "EigenLayer", "url": "https://eigenlayer.xyz", "handle": "eigenlayer", "desc": "Restaking middleware for Ethereum."},
    {"name": "Hychain", "url": "https://hychain.com", "handle": "HYCHAIN_GAMES", "desc": "L2 for web3 gaming."},
    {"name": "Xai", "url": "https://xai.games", "handle": "XAI_GAMES", "desc": "Arbitrum Orbit chain for gaming."},
    {"name": "Soneium", "url": "https://soneium.org", "handle": "soneium", "desc": "Sony's new Ethereum L2."},
    {"name": "Abstract", "url": "https://abstract.money", "handle": "AbstractChain", "desc": "Consumer-focused L2 by Pudgy Penguins."},
    {"name": "Story Protocol", "url": "https://storyprotocol.xyz", "handle": "StoryProtocol", "desc": "IP ownership implementation for AI."},
    {"name": "Morph", "url": "https://morphl2.io", "handle": "MorphL2", "desc": "Consumer Layer 2 blockchain."},
    {"name": "Initia", "url": "https://initia.xyz", "handle": "initiaFDN", "desc": "Interwoven rollup network."},
    {"name": "Union", "url": "https://union.build", "handle": "union_build", "desc": "Zero-knowledge interoperability layer."},
    {"name": "Hyperlane", "url": "https://hyperlane.xyz", "handle": "Hyperlane_xyz", "desc": "Modular interoperability framework."},
    {"name": "Tabi", "url": "https://tabi.lol", "handle": "Tabi_NFT", "desc": "Modular gaming L1 on Cosmos."},
    {"name": "Farcaster", "url": "https://farcaster.xyz", "handle": "farcaster_xyz", "desc": "Sufficiently decentralized social network."},
    {"name": "Lens Protocol", "url": "https://lens.xyz", "handle": "LensProtocol", "desc": "Social graph for web3."},
    {"name": "Aztec", "url": "https://aztec.network", "handle": "aztecnetwork", "desc": "Privacy-first L2 on Ethereum."},
    {"name": "Aleo", "url": "https://aleo.org", "handle": "AleoHQ", "desc": "L1 for zero-knowledge applications."},
    {"name": "Scroll", "url": "https://scroll.io", "handle": "Scroll_ZKP", "desc": "Native zkEVM Layer 2."},
    {"name": "Taiko", "url": "https://taiko.xyz", "handle": "taikoxyz", "desc": "Decentralized Ethereum-equivalent ZK-Rollup."},
    {"name": "Linea", "url": "https://linea.build", "handle": "LineaBuild", "desc": "Developer-ready zkEVM rollup."},
    {"name": "Base", "url": "https://base.org", "handle": "base", "desc": "Secure, low-cost Ethereum L2."},
    {"name": "Zora", "url": "https://zora.co", "handle": "ourZORA", "desc": "L2 for media and creators."},
    {"name": "Blast", "url": "https://blast.io", "handle": "Blast_L2", "desc": "L2 with native yield."},
    {"name": "Mode", "url": "https://mode.network", "handle": "modenetwork", "desc": "Modular DeFi L2."},
    {"name": "Manta", "url": "https://manta.network", "handle": "MantaNetwork", "desc": "Modular blockchain for ZK applications."},
    {"name": "AltLayer", "url": "https://altlayer.io", "handle": "alt_layer", "desc": "Rollup-as-a-Service protocol."},
    {"name": "Dymension", "url": "https://dymension.xyz", "handle": "dymension", "desc": "Network of deployable RollApps."},
    {"name": "Celestia", "url": "https://celestia.org", "handle": "CelestiaOrg", "desc": "Modular data availability network."},
    {"name": "Fuel", "url": "https://fuel.network", "handle": "fuel_network", "desc": "Modular execution layer."},
    {"name": "Eclipse", "url": "https://eclipse.builders", "handle": "EclipseFND", "desc": "Ethereum SVM L2."},
    {"name": "Fluent", "url": "https://fluentlabs.xyz", "handle": "fluentxyz", "desc": "zWasm execution layer."},
    {"name": "Risc0", "url": "https://risczero.com", "handle": "risczero", "desc": "General purpose ZK computing."},
    {"name": "Succinct", "url": "https://succinct.xyz", "handle": "SuccinctLabs", "desc": "ZK interoperability infrastructure."},
    {"name": "Polyhedra", "url": "https://polyhedra.network", "handle": "PolyhedraZK", "desc": "Web3 interoperability infrastructure."},
    {"name": "LayerZero", "url": "https://layerzero.network", "handle": "LayerZero_Labs", "desc": "Omnichain interoperability protocol."},
    {"name": "Wormhole", "url": "https://wormhole.com", "handle": "wormholecrypto", "desc": "Cross-chain connectivity platform."},
    {"name": "Axelar", "url": "https://axelar.network", "handle": "axelarcore", "desc": "Secure cross-chain communication."},
    {"name": "Noble", "url": "https://nobleassets.xyz", "handle": "noble_xyz", "desc": "Asset issuance chain for Cosmos."},
    {"name": "Kakarot", "url": "https://kakarot.org", "handle": "KakarotZkEvm", "desc": "zkEVM on Starknet."},
    {"name": "Starknet", "url": "https://starknet.io", "handle": "Starknet", "desc": "Validity Rollup L2."},
    {"name": "zkSync", "url": "https://zksync.io", "handle": "zksync", "desc": "ZK-rollup trustless protocol."},
    {"name": "Polygon zkEVM", "url": "https://polygon.technology", "handle": "0xPolygon", "desc": "Scalable zkEVM solution."},
    {"name": "Aptos", "url": "https://aptoslabs.com", "handle": "AptosLabs", "desc": "Layer 1 blockchain using Move."},
    {"name": "Sui", "url": "https://sui.io", "handle": "SuiNetwork", "desc": "Layer 1 blockchain for ownership."},
    {"name": "Sei", "url": "https://sei.io", "handle": "SeiNetwork", "desc": "Fastest L1 for trading."},
    {"name": "Injective", "url": "https://injective.com", "handle": "Injective_", "desc": "Blockchain built for finance."},
    {"name": "Nibiru", "url": "https://nibiru.fi", "handle": "NibiruChain", "desc": "DeFi hub on Cosmos."},
    {"name": "Kujira", "url": "https://kujira.app", "handle": "TeamKujira", "desc": "DeFi layer 1."},
    {"name": "Osmosis", "url": "https://osmosis.zone", "handle": "osmosiszone", "desc": "Interchain DEX."},
    {"name": "Juno", "url": "https://junonetwork.io", "handle": "JunoNetwork", "desc": "Interoperable smart contract network."},
    {"name": "Evmos", "url": "https://evmos.org", "handle": "EvmosOrg", "desc": "EVM on Cosmos."},
    {"name": "Canto", "url": "https://canto.io", "handle": "CantoPublic", "desc": "L1 for DeFi."},
    {"name": "Fantom Sonic", "url": "https://fantom.foundation", "handle": "FantomFDN", "desc": "High-throughput L1."},
    {"name": "Avail", "url": "https://availproject.org", "handle": "AvailProject", "desc": "Data availability layer."},
    {"name": "Near", "url": "https://near.org", "handle": "NEARProtocol", "desc": "Scalable L1 blockchain."},
    {"name": "Aurora", "url": "https://aurora.dev", "handle": "auroraisnear", "desc": "EVM on NEAR."},
    {"name": "Neon", "url": "https://neonevm.org", "handle": "Neon_EVM", "desc": "EVM on Solana."},
    {"name": "Arbitrum", "url": "https://arbitrum.io", "handle": "arbitrum", "desc": "Optimistic rollup L2."},
    {"name": "Optimism", "url": "https://optimism.io", "handle": "Optimism", "desc": "Ethereum L2 blockchain."},
    {"name": "Metis", "url": "https://metis.io", "handle": "MetisL2", "desc": "Decentralized Ethereum L2."},
    {"name": "Boba", "url": "https://boba.network", "handle": "bobanetwork", "desc": "L2 with hybrid compute."},
    {"name": "Redacted", "url": "https://redacted.cartel.xyz", "handle": "redactedcartel", "desc": "DeFi ecosystem."},
    {"name": "GMX", "url": "https://gmx.io", "handle": "GMX_IO", "desc": "Decentralized perpetual exchange."},
    {"name": "Synthetix", "url": "https://synthetix.io", "handle": "synthetix_io", "desc": "Liquidity protocol."},
    {"name": "Aave", "url": "https://aave.com", "handle": "aave", "desc": "Open source liquidity protocol."},
    {"name": "Curve", "url": "https://curve.fi", "handle": "CurveFinance", "desc": "Stablecoin exchange."},
    {"name": "Uniswap", "url": "https://uniswap.org", "handle": "Uniswap", "desc": "Decentralized trading protocol."},
    {"name": "Sushi", "url": "https://sushi.com", "handle": "SushiSwap", "desc": "Multi-chain DEX."},
    {"name": "PancakeSwap", "url": "https://pancakeswap.finance", "handle": "PancakeSwap", "desc": "DEX on BNB Chain."},
    {"name": "Jupiter", "url": "https://jup.ag", "handle": "JupiterExchange", "desc": "Solana swap aggregator."},
    {"name": "Pyth", "url": "https://pyth.network", "handle": "PythNetwork", "desc": "First-party oracle network."},
    {"name": "Chainlink", "url": "https://chain.link", "handle": "chainlink", "desc": "Decentralized oracle network."},
    {"name": "The Graph", "url": "https://thegraph.com", "handle": "graphprotocol", "desc": "Indexing protocol."},
    {"name": "Arweave", "url": "https://arweave.org", "handle": "ArweaveEco", "desc": "Permanent information storage."},
    {"name": "Filecoin", "url": "https://filecoin.io", "handle": "Filecoin", "desc": "Decentralized storage network."},
    {"name": "Render", "url": "https://rendernetwork.com", "handle": "rendernetwork", "desc": "Distributed GPU rendering."},
    {"name": "Akash", "url": "https://akash.network", "handle": "akashnet_", "desc": "Decentralized cloud computing."},
    {"name": "Gensyn", "url": "https://gensyn.ai", "handle": "gensynai", "desc": "Compute protocol for AI."},
    {"name": "Bittensor", "url": "https://bittensor.com", "handle": "bittensor_", "desc": "Peer-to-peer intelligence market."},
    {"name": "Worldcoin", "url": "https://worldcoin.org", "handle": "worldcoin", "desc": "Proof of personhood."},
    {"name": "Safe", "url": "https://safe.global", "handle": "safe", "desc": "Smart wallet infrastructure."},
    {"name": "WalletConnect", "url": "https://walletconnect.com", "handle": "WalletConnect", "desc": "Web3 communications protocol."},
    {"name": "Privy", "url": "https://privy.io", "handle": "privy_io", "desc": "Authentication infrastructure."},
    {"name": "Dynamic", "url": "https://dynamic.xyz", "handle": "dynamic_xyz", "desc": "Wallet intelligence."},
    {"name": "Clerk", "url": "https://clerk.com", "handle": "clerkdev", "desc": "Authentication for React."},
    {"name": "Thirdweb", "url": "https://thirdweb.com", "handle": "thirdweb", "desc": "Web3 development framework."},
    {"name": "Alchemy", "url": "https://alchemy.com", "handle": "AlchemyPlatform", "desc": "Web3 developer platform."},
    {"name": "Infura", "url": "https://infura.io", "handle": "infura_io", "desc": "Blockchain development suite."},
    {"name": "QuickNode", "url": "https://quicknode.com", "handle": "QuickNode", "desc": "Blockchain infrastructure."},
    {"name": "Flashbots", "url": "https://flashbots.net", "handle": "FlashbotsFDN", "desc": "MEV mitigation."},
    {"name": "Lido", "url": "https://lido.fi", "handle": "LidoFinance", "desc": "Liquid staking solution."},
    {"name": "Rocket Pool", "url": "https://rocketpool.net", "handle": "Rocket_Pool", "desc": "Decentralized ETH staking."},
    {"name": "Ether.fi", "url": "https://ether.fi", "handle": "ether_fi", "desc": "Liquid restaking protocol."},
    {"name": "Puffer", "url": "https://puffer.fi", "handle": "puffer_finance", "desc": "Liquid restaking protocol."},
    {"name": "Renzo", "url": "https://renzoprotocol.com", "handle": "RenzoProtocol", "desc": "Liquid restaking token."},
    {"name": "Kelp DAO", "url": "https://kelpdao.xyz", "handle": "KelpDAO", "desc": "Liquid restaking optimization."},
    {"name": "Swell", "url": "https://swellnetwork.io", "handle": "swellnetworkio", "desc": "Liquid staking protocol."},
    {"name": "Parcl", "url": "https://parcl.co", "handle": "Parcl", "desc": "Real estate trading."},
    {"name": "Tensor", "url": "https://tensor.trade", "handle": "tensor_hq", "desc": "Solana NFT marketplace."},
    {"name": "Magic Eden", "url": "https://magiceden.io", "handle": "MagicEden", "desc": "Cross-chain NFT marketplace."},
    {"name": "Blur", "url": "https://blur.io", "handle": "blur_io", "desc": "NFT marketplace for pro traders."},
    {"name": "OpenSea", "url": "https://opensea.io", "handle": "opensea", "desc": "Largest NFT marketplace."},
    {"name": "Yuga Labs", "url": "https://yuga.com", "handle": "yugalabs", "desc": "Creators of BAYC."},
    {"name": "Doodles", "url": "https://doodles.app", "handle": "doodles", "desc": "Community-driven collectibles."},
    {"name": "Pudgy Penguins", "url": "https://pudgypenguins.com", "handle": "pudgypenguins", "desc": "Web3 IP brand."},
    {"name": "Azuki", "url": "https://azuki.com", "handle": "Azuki", "desc": "Anime-inspired brand."},
    {"name": "DeGods", "url": "https://degods.com", "handle": "DeGodsNFT", "desc": "Digital art collection."},
    {"name": "Memeland", "url": "https://memeland.com", "handle": "Memeland", "desc": "Community venture studio."},
    {"name": "9dcc", "url": "https://9dcc.xyz", "handle": "9dccxyz", "desc": "Networked products."}
]
